packageExtensions:
  "@chakra-ui/styled-system@1.3.0":
    dependencies:
      lodash.mergewith: "*"
  "@chakra-ui/styled-system@1.5.0":
    dependencies:
      lodash.mergewith: "*"
  "@fortawesome/react-fontawesome@*":
     dependencies:
      "@fortawesome/fontawesome-svg-core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: /Users/vincent/Code/bundless-try/.yarn/releases/yarn-berry.js
